prom_con_exp:
  image: prom/container-exporter 
  ports:
   -  "9104:9104"
  volumes:
   - "/sys/fs/cgroup:/cgroup"   
  volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
alert_manager:
  image: prom/alertmanager
  ports:
   -  "9093:9093"
  volumes:
   - "$PWD/alertmanager.conf:/alertmanager.conf"
  command: -config.file=/alertmanager.conf
prom_prometheus:
  image: prom/prometheus
  ports:
   -  "9090:9090"
  volumes:
   - "$PWD/prometheus.yml:/etc/prometheus/prometheus.yml"
  volumes:
   - "$PWD/alert.rules:/etc/prometheus/alert.rules"
  command: -config.file=/etc/prometheus/prometheus.yml -alertmanager.url=http://localhost:9093
prom_dash:
  image: prom/promdash
  ports:
   -  "4000:3000"
  volumes:
   - "$PWD:/tmp/prom"
  environment:
     DATABASE_URL: sqlite3:/tmp/prom/promdash.sqlite3
